# lang.py
LANGUAGE_CONFIG = {
    "en": {
        "title": "## AEI CoT-Lab: AI-Enhanced Learning Laboratory \n**American Education Institute** - Empowering Education Through AI Innovation  \nSynchronize your thinking with advanced AI reasoning for deeper learning outcomes",
        "prompt_label": "Learning Objective",
        "prompt_placeholder": "Enter your learning question or educational goal...",
        "editor_label": "AEI Collaborative Thinking Space",
        "editor_placeholder": "The AI tutor's reasoning will appear here... Edit to guide the learning process",
        "generate_btn": "Generate",
        "pause_btn": "Pause",
        "sync_threshold_label": "🧠 Human Thinking Cadence",
        "sync_threshold_info": "Pause for human turn per X paragraphs",
        "throughput_label": "⏱ Sync Rate",
        "throughput_info": "Tokens/s - 5:Learn, 10:Follow, 50:Skim",
        "language_label": "Language",
        "loading_thinking": "🤖 AI Thinking ↓ Shift+Enter to Pause",
        "loading_output": "🖨️ Result Writing → (Pause & submit to reroll the result)",
        "interrupted": "🤔 Pause, Human thinking time - **EDIT THOUGHTS BELOW**",
        "completed": "✅ Completed → Check overview",
        "error": "Error",
        "api_config_label": "API Configuration",
        "api_key_label": "API Key",
        "api_key_placeholder": "Leave empty to use environment variable",
        "api_url_label": "API URL",
        "api_url_placeholder": "Leave empty for default URL",
        "clear_btn": "Clear Thinking",
        "introduction": "Think together with AI. Use `Shift+Enter` to toggle generation <br>You can modify the thinking process when AI pauses",
        "bot_label": "Conversation Overview",
        "bot_default": [
            {
                "role": "assistant",
                "content": "Welcome to the **American Education Institute's AI-Enhanced Learning Laboratory**! \n\nI'm your AEI AI tutor, ready to guide you through personalized learning experiences. \n\n📚 Adjust the thinking speed to match your learning pace, then share your educational goals. Together, we'll explore concepts deeply and build understanding step by step.",
            },
        ],
        "editor_default": "AI thought will start with this, leave blank to think freely",
        "waiting_api": "⏳ Waiting for API response",
        "api_retry": "🔁 API no response, hit Shift+Enter to try again.",
        "api_interrupted": "⚠️ Pasued, API connection interrupted. Hit Shift+Enter to reconnect",
        "result_editing_toggle": "Editor includes Result"

    },
    "zh": {
        "title": "## AEI CoT-Lab: AI增强学习实验室\n**美国教育学院** - 通过AI创新赋能教育  \n与先进的AI推理同步思考，实现更深层次的学习成果",
        "prompt_label": "学习目标",
        "prompt_placeholder": "输入您的学习问题或教育目标...",
        "editor_label": "AEI协作思考空间",
        "editor_placeholder": "AI导师的推理过程将在此显示...编辑以引导学习过程",
        "generate_btn": "生成",
        "pause_btn": "暂停",
        "sync_threshold_label": "🧠 人类思考间隔",
        "sync_threshold_info": "段落数 - 每X段落自动暂停进入人类思考时间",
        "throughput_label": "⏱ 同步思考速度",
        "throughput_info": "词元/秒 - 5:学习, 10:跟读, 50:跳读",
        "language_label": "界面语言",
        "loading_thinking": "🤖 AI思考中 ↓ Shift+Enter可暂停",
        "loading_output": "🖨️ 结果输出中 → (暂停再提交会重新生成结果部分)",
        "interrupted": "🤔 暂停，人类思考回合 **下面的思考过程可以编辑**",
        "completed": "✅ 已完成 → 查看完整对话",
        "error": "错误",
        "api_config_label": "API配置",
        "api_key_label": "API密钥",
        "api_key_placeholder": "留空使用环境变量",
        "api_url_label": "API地址",
        "api_url_placeholder": "留空使用默认地址",
        "clear_btn": "清空思考",
        "introduction": "和AI一起思考，Shift+Enter切换生成状态<br>AI暂停的时候你可以编辑思维过程",
        "bot_label": "对话一览",
        "bot_default": [
            {
                "role": "assistant",
                "content": "欢迎来到**美国教育学院的AI增强学习实验室**！\n\n我是您的AEI AI导师，准备引导您完成个性化的学习体验。\n\n📚 调整思考速度以匹配您的学习节奏，然后分享您的教育目标。我们将一起深入探索概念，逐步建立理解。",
            },
        ],
        "editor_default": "AI思维会以此开头，留空即为默认思考",
        "waiting_api": "⏳ 等待API响应",
        "api_retry": "🔁 API无响应, Shift+Enter 重试一次试试？",
        "api_interrupted": "⚠️ 暂停，API连接意外中断，Shift+Enter 可重连",
        "result_editing_toggle": "编辑器包括最终答案"

    },
}
